/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
      extend: {
          colors: {
              "surface-variant": "#d9e3f4",
              "outline-variant": "#c0c9c2",
              "surface-dim": "#d1dbec",
              "surface": "#f8f9ff",
              "surface-tint": "#306952",
              "tertiary-fixed": "#92f7c3",
              "on-background": "#121c28",
              "primary-fixed": "#b3efd2",
              "tertiary-container": "#004b30",
              "secondary-fixed": "#b1f0ce",
              "outline": "#707973",
              "secondary": "#2c694e",
              "surface-container-highest": "#d9e3f4",
              "tertiary-fixed-dim": "#75daa8",
              "on-secondary": "#ffffff",
              "on-secondary-fixed": "#002114",
              "primary-fixed-dim": "#98d3b7",
              "primary": "#003222",
              "on-tertiary-fixed": "#002113",
              "tertiary": "#00321f",
              "inverse-surface": "#27313e",
              "secondary-fixed-dim": "#95d4b3",
              "on-tertiary-fixed-variant": "#005235",
              "on-primary-fixed": "#002115",
              "on-surface": "#121c28",
              "secondary-container": "#aeeecb",
              "surface-container": "#e5eeff",
              "on-primary-container": "#7fb99e",
              "on-error-container": "#93000a",
              "background": "#f8f9ff",
              "surface-container-low": "#eef4ff",
              "on-tertiary-container": "#5bbf90",
              "surface-container-high": "#dfe9fa",
              "on-error": "#ffffff",
              "surface-container-lowest": "#ffffff",
              "error-container": "#ffdad6",
              "error": "#ba1a1a",
              "on-secondary-fixed-variant": "#0e5138",
              "on-primary-fixed-variant": "#14503b",
              "primary-container": "#0a4a35",
              "on-tertiary": "#ffffff",
              "inverse-primary": "#98d3b7",
              "surface-bright": "#f8f9ff",
              "on-primary": "#ffffff",
              "on-surface-variant": "#404944",
              "inverse-on-surface": "#eaf1ff",
              "on-secondary-container": "#316e52"
          },
          borderRadius: {
              "DEFAULT": "0.125rem",
              "lg": "0.25rem",
              "xl": "0.5rem",
              "full": "0.75rem"
          },
          spacing: {
              "calendar-cell-min-height": "7.5rem",
              "sidebar-width": "16rem",
              "space-2xl": "3rem",
              "space-xs": "0.5rem",
              "space-lg": "1.5rem",
              "sidebar-collapsed-width": "4.5rem",
              "space-md": "1rem",
              "space-xl": "2rem",
              "space-2xs": "0.25rem",
              "space-sm": "0.75rem"
          },
          fontFamily: {
              "label-sm": ["Inter", "sans-serif"],
              "headline-md": ["Inter", "sans-serif"],
              "title-sm": ["Inter", "sans-serif"],
              "body-sm": ["Inter", "sans-serif"],
              "body-md": ["Inter", "sans-serif"],
              "title-md": ["Inter", "sans-serif"],
              "headline-xl-mobile": ["Inter", "sans-serif"],
              "body-lg": ["Inter", "sans-serif"],
              "headline-lg": ["Inter", "sans-serif"],
              "label-md": ["Inter", "sans-serif"],
              "headline-xl": ["Inter", "sans-serif"]
          },
          fontSize: {
              "label-sm": ["11px", { "lineHeight": "14px", "letterSpacing": "0.04em", "fontWeight": "600" }],
              "headline-md": ["20px", { "lineHeight": "28px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
              "title-sm": ["14px", { "lineHeight": "20px", "fontWeight": "600" }],
              "body-sm": ["12px", { "lineHeight": "16px", "fontWeight": "400" }],
              "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
              "title-md": ["16px", { "lineHeight": "24px", "letterSpacing": "-0.005em", "fontWeight": "600" }],
              "headline-xl-mobile": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
              "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
              "headline-lg": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.015em", "fontWeight": "600" }],
              "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.01em", "fontWeight": "500" }],
              "headline-xl": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700" }]
          }
      }
  },
  plugins: [],
}
